export const SET_IS_HOTELS_VISIBLE = 'SET_IS_HOTEL_VISIBLE';
export const SET_IS_OPTIONS_VISIBLE = 'SET_IS_OPTIONS_VISIBLE';
export const SET_IS_CALENDAR_VISIBLE = 'SET_IS_CALENDAR_VISIBLE';
export const SET_IS_LOGOUT_VISIBLE = 'SET_IS_LOGOUT_VISIBLE';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_FOUND_HOTELS = 'SET_FOUND_HOTELS';
export const SET_ADULTS_NUMBER = 'SET_ADULTS_NUMBER_PLUS';
export const SET_CHILDREN_NUMBER = 'SET_CHILDREN_NUMBER_PLUS';
export const SET_ROOMS_NUMBER = 'SET_ROOMS_NUMBER_PLUS';
export const SET_VISITING_DATES = 'SET_VISITING_DATES';
export const SET_PREV_CALENDAR_MONTH = 'SET_PREV_CALENDAR_MONTH';
export const SET_NEXT_CALENDAR_MONTH = 'SET_NEXT_CALENDAR_MONTH';
export const SET_PREV_CALENDAR_YEAR = 'SET_PREV_CALENDAR_YEAR';
export const SET_NEXT_CALENDAR_YEAR = 'SET_NEXT_CALENDAR_YEAR';
export const SET_HOMES_HOTELS = 'SET_HOMES_HOTELS';
export const SET_USER_NAME_INPUT = 'SET_USER_NAME_INPUT';
export const SET_USER_PASSWORD_INPUT = 'SET_USER_PASSWORD_INPUT';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
export const SET_HOTEL_INFO = 'SET_HOTEL_INFO';



